// Add your dependencies here

dependencies {
    devOnlyNonPublishable('com.github.GTNewHorizons:NotEnoughItems:2.8.130-GTNH:dev')
    compileOnly('com.github.GTNewHorizons:Angelica:2.2.11:dev')
    compileOnly("com.github.GTNewHorizons:waila:1.19.34:dev") { transitive = false }
    api("com.github.GTNewHorizons:ModularUI2:2.3.88-1.7.10:dev")
    shadowImplementation("io.github.earcut4j:earcut4j:2.2.2")
}
