// Add your dependencies here

dependencies {
    devOnlyNonPublishable('com.github.GTNewHorizons:NotEnoughItems:2.8.125-GTNH:dev')
    compileOnly('com.github.GTNewHorizons:Angelica:2.2.7:dev')
    compileOnly("com.github.GTNewHorizons:waila:1.19.31:dev") { transitive = false }
    api("com.github.GTNewHorizons:ModularUI2:2.3.85-1.7.10:dev")
    shadowImplementation("io.github.earcut4j:earcut4j:2.2.2")
}
